# nothing here
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=32768

CONFIG_SHELL=y

CONFIG_FLASH=y
CONFIG_FLASH_SHELL=y
CONFIG_FLASH_SHELL_TEST_COMMANDS=y
CONFIG_FLASH_SHELL_BUFFER_SIZE=20000
CONFIG_FLASH_MAP=y
CONFIG_FLASH_MAP_SHELL=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FS_LITTLEFS_READ_SIZE=2048
CONFIG_FS_LITTLEFS_PROG_SIZE=2048
CONFIG_FS_LITTLEFS_CACHE_SIZE=2048

CONFIG_HEAP_MEM_POOL_SIZE=32768

CONFIG_GPIO_PCA_SERIES=n
