CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=32768

CONFIG_DISK_LOG_LEVEL_DBG=y
CONFIG_DMA_LOG_LEVEL_DBG=y
CONFIG_FLASHDISK_LOG_LEVEL_DBG=y
CONFIG_FLASH_LOG_LEVEL_DBG=y
CONFIG_FS_LOG_LEVEL_DBG=y
CONFIG_MEMC_LOG_LEVEL_DBG=y

CONFIG_SHELL=y

CONFIG_FLASH=y
CONFIG_FLASH_SHELL=y
CONFIG_FLASH_SHELL_TEST_COMMANDS=y
CONFIG_FLASH_SHELL_BUFFER_SIZE=0x30000
CONFIG_FLASH_MAP=y
CONFIG_FLASH_MAP_SHELL=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_MAX_SS=2048
CONFIG_FS_FATFS_MIN_SS=2048
CONFIG_FS_FATFS_FSTAB_AUTOMOUNT=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=32768

CONFIG_GPIO_PCA_SERIES=n
